image:
  repository: danisla/hadoop
  tag: 2.9.0
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 2.9.0

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "hard"
hdfs:
  nameNode:
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  dataNode:
    replicas: 1
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  webhdfs:
    enabled: false

yarn:
  resourceManager:
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
    nodeManager:
      pdbMinAvailable: 1
      # The number of YARN NodeManager instances.
      replicas: 1
      # Create statefulsets in parallel (K8S 1.7+)
      parallelCreate: false

      # CPU and memory resources allocated to each node manager pod.
      # This should be tuned to fit your workload.
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "1000m"
persistence:
  nameNode:
    enabled: true
    storageClass: "managed-nfs-storage"
    accessMode: ReadWriteOnce
    size: 100Gi
  dataNode:
    enabled: true
    storageClass: "managed-nfs-storage"
    reclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 100Gi
