spring:
    hadoop:
        fsUri: hdfs://localhost:9000
        resourceManagerHost: localhost
    yarn:
        appName: yarn-boot-simple
        applicationDir: /app/yarn-boot-simple/
        client:
            files:
                - "file:target/yarn-boot-simple-container-0.1.0.jar"
                - "file:target/yarn-boot-simple-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: yarn-boot-simple-appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: yarn-boot-simple-container-0.1.0.jar