spring:
    hadoop:
        fsUri: hdfs://192.168.1.119:30051
        resourceManagerHost: 192.168.1.119
        resourceManagerAddress: 192.168.1.119:32458
    yarn:
        appName: yarn-boot-simple
        applicationDir: /app/yarn-boot-simple/
        fsUri: hdfs://192.168.1.119:30051
        rmAddress: 192.168.1.119:32458
        client:
            files:
                - "file:build/libs/yarn-boot-simple-container-0.1.0.jar"
                - "file:build/libs/yarn-boot-simple-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: yarn-boot-simple-appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: yarn-boot-simple-container-0.1.0.jar