spring:
  hadoop:
    fsUri: hdfs://localhost:900
    resourceManagerHost: localhost
  yarn:
    appName: spring-yarn
    applicationDir: /app/spring-yarn/
    client:
      files:
        - "file:yarn-container/target/yarn-container-0.0.1-SNAPSHOT.jar"
        - "file:yarn-container/target/yarn-master-0.0.1-SNAPSHOT.jar"
      launchcontext:
        archiveFile: yarn-boot-simple-appmaster-0.1.0.jar
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: yarn-boot-simple-container-0.1.0.jar