spring:
  hadoop:
    fsUri: hdfs://localhost:9000
    resourceManagerAddress: localhost:8032
    jobHistoryAddress: 
    config:
      fs.defaultFS: hdfs://localhost:8020

((HadoopConfigConfigurer)((HadoopConfigConfigurer)config.fileSystemUri(this.shp.getFsUri()).resourceManagerAddress(this.shp.getResourceManagerAddress()).jobHistoryAddress(this.shp.getJobHistoryAddress()).withProperties().properties(this.shp.getConfig()).and()).withResources().resources(this.shp.getResources()).and()).withSecurity().namenodePrincipal(this.shp.getSecurity() != null ? this.shp.getSecurity().getNamenodePrincipal() : null).rmManagerPrincipal(this.shp.getSecurity() != null ? this.shp.getSecurity().getRmManagerPrincipal() : null).authMethod(this.shp.getSecurity() != null ? this.shp.getSecurity().getAuthMethod() : null).userPrincipal(this.shp.getSecurity() != null ? this.shp.getSecurity().getUserPrincipal() : null).userKeytab(this.shp.getSecurity() != null ? this.shp.getSecurity().getUserKeytab() : null);

  yarn:
    appName: spring-yarn
    applicationDir: /app/spring-yarn/
    fsUri: hdfs://localhost:9000
    rmAddress: localhost:8032
    schedulerAddress: localhost:8032
    client:
      files:
        - "file:/Users/mac/Documents/projects/Agilion/spring-yarn/yarn_container/target/yarn_container-0.0.1-SNAPSHOT.jar"
        - "file:/Users/mac/Documents/projects/Agilion/spring-yarn/yarn_appmaster/target/yarn_appmaster-0.0.1-SNAPSHOT.jar"
      launchcontext:
        archiveFile: yarn_appmaster-0.0.1-SNAPSHOT.jar
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: yarn_container-0.0.1-SNAPSHOT.jar
