spring:
  hadoop:
    fsUri: hdfs://localhost:9000
    resourceManagerHost: localhost
    rmAddress: localhost
  yarn:
    appName: spring-yarn
    applicationDir: /app/spring-yarn/
    fsUri: hdfs://localhost:9000
    rmAddress: localhost:8032
    schedulerAddress: localhost:8032